spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devopsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devopsuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
